### ISSUE TITLE
Glossary spells "Ygdrasil" with one L but text spells it with two

### ISSUE THREAD

**Issue by apasel422** [standardebooks/thomas-bulfinch_bulfinchs-mythology#8]
https://github.com/standardebooks/thomas-bulfinch_bulfinchs-mythology/blob/00b3b7363eb075ffaad3cfb8ca74f40f02ca9dbc/src/epub/text/glossary.xhtml#L7951

https://github.com/standardebooks/thomas-bulfinch_bulfinchs-mythology/blob/00b3b7363eb075ffaad3cfb8ca74f40f02ca9dbc/src/epub/glossary-search-key-map.xml#L4059

https://github.com/standardebooks/thomas-bulfinch_bulfinchs-mythology/blob/00b3b7363eb075ffaad3cfb8ca74f40f02ca9dbc/src/epub/text/chapter-1-38.xhtml#L20

This appears to be present in the original sources:

https://www.gutenberg.org/cache/epub/56644/pg56644-images.html#s38
https://archive.org/details/bulfinchsmytholo1913bulf/page/911/mode/2up

Complicating matters is that it seems to be spelled differently in Old Norse and in modern English, and even multiple `L`s seem to be accepted as an alternative spelling today, though the lone `G` seems somewhat rarer.

https://en.wiktionary.org/wiki/Yggdrasil

Perhaps we should just use all four forms in the glossary?

**Comment by acabal** [comment]
I'm more familiar with `Yggdrasil` so let's standardize on that.

**Comment by acabal** [comment]
I'll do that on my end
